apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kyma-system
  name: github-oidc-role
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "watch", "list", "create", "update", "delete" ]
  - apiGroups: [ "operator.kyma-project.io" ]
    resources: [ "moduletemplates" ]
    verbs: [ "get", "watch", "list", "create", "update", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-oidc-binding
  namespace: kyma-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-oidc-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: actions-oidc:repo:ruanxin/kcp-oidc:ref:refs/heads/main