name: push-ocm-image-to-kcp-registry

permissions:
  id-token: write
on:
  workflow_dispatch:
jobs:
  push-image:
    runs-on: ubuntu-latest
    env:
      API_SERVER: https://api.kcp-oidc.jellyfish.shoot.canary.k8s-hana.ondemand.com
      REGISTRY_URL: https://registry.ingress.kcp-oidc.jellyfish.shoot.canary.k8s-hana.ondemand.com
    steps:
      - name: configure OIDC
        id: create-oidc-token
        run: |
          AUDIENCE="gh-kubernetes-action" # clientID
          OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"

          IDTOKEN=$(curl \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            -H "Accept: application/json; api-version=2.0" \
            "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)
          
          echo "::add-mask::${IDTOKEN}"
          echo "::set-output name=idToken::${IDTOKEN}"
          # Print decoded token information for debugging purposes
          echo $IDTOKEN | jq -R 'split(".") | .[1] | @base64d | fromjson'
      - name: Check Permissions in Kubernetes
        run: |
          echo "${{ secrets.API_SERVER_CA }}" | base64 -d > /tmp/ca.crt
          kubectl --token=${{ steps.create-oidc-token.outputs.IDTOKEN }} --server="$API_SERVER" --certificate-authority="/tmp/ca.crt" auth can-i --list --namespace kyma-system
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Checkout Template Operator
        uses: actions/checkout@v4
        with:
          repository: kyma-project/template-operator
          path: template-operator
      - name: Install Kyma CLI
        run: |
          wget https://storage.googleapis.com/kyma-cli-unstable/kyma-linux
          chmod +x kyma-linux && mv kyma-linux /usr/local/bin/kyma-unstable
          ln -s /usr/local/bin/kyma-unstable /usr/local/bin/kyma
      - name: Deploy ingress
        run: |
          kubectl --token=${{ steps.create-oidc-token.outputs.IDTOKEN }} --server="$API_SERVER" --certificate-authority="/tmp/ca.crt" apply -f repo/ingress.yaml
      - name: Create Template Operator Module and push to OCI registry
        working-directory: template-operator
        run: |
          OCI_USERNAME=$(kubectl --token=${{ steps.create-oidc-token.outputs.IDTOKEN }} --server="$API_SERVER" --certificate-authority="/tmp/ca.crt" get secret -n kyma-system serverless-registry-config-default -o jsonpath="{.data.username}" | base64 -d)
          OCI_PASSWORD=$(kubectl --token=${{ steps.create-oidc-token.outputs.IDTOKEN }} --server="$API_SERVER" --certificate-authority="/tmp/ca.crt" get secret -n kyma-system serverless-registry-config-default -o jsonpath="{.data.password}" | base64 -d)
          make build-manifests
          date=0.1.2-$(date '+%Y%m%d%M%S') yq -i '.version=env(date)' ./module-config.yaml
          less ./module-config.yaml
          kyma alpha create module --module-config-file ./module-config.yaml --path . --registry $REGISTRY_URL -c ${OCI_USERNAME}:${OCI_PASSWORD}
      - name: Delete ingress
        run: |
          kubectl --token=${{ steps.create-oidc-token.outputs.IDTOKEN }} --server="$API_SERVER" --certificate-authority="/tmp/ca.crt" delete -f repo/ingress.yaml