name: push-ocm-image-to-kcp-registry

permissions:
  id-token: write
on:
  workflow_dispatch:
jobs:
  push-image:
    runs-on: ubuntu-latest
    env:
      API_SERVER: https://api.kcp-oidc.jellyfish.shoot.canary.k8s-hana.ondemand.com
      CLUSTER_KUBECONFIG_PATH: /tmp/cluster_kubeconfig.yaml
    steps:
      - name: configure OIDC
        id: create-oidc-token
        run: |
          AUDIENCE="gh-kubernetes-action" # clientID
          OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"

          IDTOKEN=$(curl \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            -H "Accept: application/json; api-version=2.0" \
            "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)
          
          echo "::add-mask::${IDTOKEN}"
          echo "::set-output name=idToken::${IDTOKEN}"
          # Print decoded token information for debugging purposes
          echo $IDTOKEN | jq -R 'split(".") | .[1] | @base64d | fromjson'
      - name: Check Permissions in Kubernetes
        run: |
          kubectl \
          --token=${{ steps.create-oidc-token.outputs.IDTOKEN }} \
          --server="$API_SERVER" \
          --certificate-authority="${{ secrets.API_SERVER_CA }}" \
          auth can-i --list --namespace kyma-system      
